---
title: "Genomic context of variably-methylated repetitive elements in mouse"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

# Introduction

This site contains the analyses related to _Genomic context of variably-methylated repetitive elements in mouse_, a manuscript by Jessica Elmer, Amir Hay, and Noah Kessler, under the supervision of Prof. Anne Ferguson-Smith.

See [our bioRxiv submission](https://www.biorxiv.org/content/10.1101/2020.10.21.349217v1).

# Analyses

## IAP annotations

This analysis helped fix issues with the RepeatMasker annotations of IAPs.
See [01.IAP_Annotations.html](01.IAP_Annotations.html).

## Updated screen for VM-IAPs

An update of the screen for VM-IAPs, similar to that performed in Kazachenka & Bertozzi _et al_., using the improved reference and with some improvements in implementation.
See [02.Screen_for_VM_IAP.html](02.Screen_for_VM_IAP.html).

## Structure of IAPs

An overview of how IAPs are structured in terms of type (e.g. IAPLTR1a_Mm) and completeness (solo vs. incomplete/full), as well as a look into how the IAP LTRs are structured in terms of their U5, R, and U3 components.
See [03.IAP_Structure.html](03.IAP_Structure.html).

## IAP sequence

Using _k_-mer analysis, specific sequences enriched in the VM-IAPs are identified.
See [04.IAP_Sequence.html](04.IAP_Sequence.html).

## CTCF binding

An analysis of CTCF motifs and ChIP-seq data at IAPs, and how c/tsVM-IAPs differ from the rest of the IAPs.
See [05.CTCF_at_IAPs.html](05.CTCF_at_IAPs.html).

## Methylation patterns beyond IAP boundaries

We analysed whether there are any common methylation signatures in the regions flanking VM-IAPs, and found that there is little in common among the elements.
See [06.Methylation_outside_the_IAP.html](06.Methylation_outside_the_IAP.html).

## Genomic interactions with IAPs

4C-seq was performed on five IAPs (four VM-IAPs and one control hypermethylated IAP).
We found that the VM-IAPs with low methylation levels had more varied interactions with nearby genomic regions compared with the highly-methylated VM-IAPs.
See [07.Genomic_Interactions_with_IAPs.html](07.Genomic_Interactions_with_IAPs.html).

## Expansion of screen to other repeat classes

We sought to determine whether variable methylation is mostly an IAP-specific phenomemon, and found that LINEs, SINEs, and non-ERV LTRs are depleted for variably-methylated elements.
See [08.Screen_for_non_IAP_VM.html](08.Screen_for_non_IAP_VM.html).

